version: "3"

tasks:
  # Wailsアプリ の初期設定を行います
  init:
    cmds:
      - npm install
      - npm run format
    silent: true

  # テンプレートからソースコードを生成します
  generate:
    cmds:
      - npm run generate
      - npm run format
    silent: true

  # Wailsアプリ を開発モードで起動します
  dev:
    cmds:
      - wails dev -loglevel "Warning"
    silent: true

  # Wailsアプリ をビルドします
  build:
    cmds:
      - wails build
    silent: true

  # ソースコードの静的解析を実行します
  lint:
    cmds:
      - npm run lint
    silent: true

  # コードを整形します
  format:
    cmds:
      - npm run format
    silent: true

  # 単体テストを実施します
  test:
    cmds:
      - npm run test
    silent: true

  # Vitest UI を起動します
  test:ui:
    cmds:
      - npm run test:ui
    silent: true

  # npm package にアップデートがないかを確認します
  ncu:
    cmds:
      - npx npm-check-updates -i --format group
    silent: true
