// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOS() {
  return window['go']['portalcore']['Core']['GetOS']();
}

export function SetContext(arg1) {
  return window['go']['portalcore']['Core']['SetContext'](arg1);
}

export function SignIn() {
  return window['go']['portalcore']['Core']['SignIn']();
}

export function UpdateSession() {
  return window['go']['portalcore']['Core']['UpdateSession']();
}
