// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetContext(arg1) {
  return window['go']['gakusimapp']['App']['SetContext'](arg1);
}

export function SimulateContest() {
  return window['go']['gakusimapp']['App']['SimulateContest']();
}
