// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['homeapp']['HomeApp']['Greet'](arg1);
}

export function SetContext(arg1) {
  return window['go']['homeapp']['HomeApp']['SetContext'](arg1);
}
